const loginFields = [
  {
    labelText: "Username",
    labelFor: "username",
    id: "username",
    name: "username",
    type: "text",
    autoComplete: "username",
    isRequired: true,
    placeholder: "Username",
  },
  {
    labelText: "Password",
    labelFor: "password",
    id: "password",
    name: "password",
    type: "password",
    autoComplete: "current-password",
    isRequired: true,
    placeholder: "Password",
  },
];

const signupFields = [
  {
    labelText: "First name",
    labelFor: "first_name",
    id: "first_name",
    name: "first_name",
    type: "text",
    autoComplete: "first_name",
    isRequired: true,
    placeholder: "First name",
  },
  {
    labelText: "Last name",
    labelFor: "last_name",
    id: "last_name",
    name: "last_name",
    type: "text",
    autoComplete: "last_name",
    isRequired: true,
    placeholder: "Surname",
  },
  {
    labelText: "Username",
    labelFor: "username",
    id: "username",
    name: "username",
    type: "text",
    autoComplete: "username",
    isRequired: true,
    placeholder: "Username",
  },
  {
    labelText: "Email address",
    labelFor: "email-address",
    id: "email",
    name: "email",
    type: "email",
    autoComplete: "email",
    isRequired: true,
    placeholder: "Email address",
  },
  {
    labelText: "Password",
    labelFor: "password",
    id: "password1",
    name: "password",
    type: "password",
    autoComplete: "current-password",
    isRequired: true,
    placeholder: "Password",
  },
  {
    labelText: "Confirm Password",
    labelFor: "confirm-password",
    id: "password2",
    name: "confirm-password",
    type: "password",
    autoComplete: "confirm-password",
    isRequired: true,
    placeholder: "Confirm Password",
  },
];
const becomeVendorFields = [
  {
    labelText: "Store Name",
    labelFor: "store-name",
    id: "storeName",
    name: "store-name",
    type: "text",
    autoComplete: "store-name",
    isRequired: true,
    placeholder: "Store Name",
  },
  {
    labelText: "Store Category",
    labelFor: "store-category",
    id: "storeCategory",
    name: "store-category",
    type: "text",
    autoComplete: "store-category",
    isRequired: true,
    placeholder: "Store Category",
  },
  {
    labelText: "Store Nickname",
    labelFor: "store-nickname",
    id: "storeNickname",
    name: "store-nickname",
    type: "text",
    autoComplete: "store-nickname",
    isRequired: false,
    placeholder: "Store Popular Name (Optional)",
  },
  {
    labelText: "Store Abbrivation",
    labelFor: "store-abbv",
    id: "storeAbbv",
    name: "store-abbv",
    type: "text",
    autoComplete: "store-abbv",
    isRequired: false,
    placeholder: "Store Short Name (Optional)",
  },
];
export { loginFields, signupFields, becomeVendorFields };
